include:
  - board: seeeduino_xiao_ble
    shield: cornex_left rgbled_adapter
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao_ble
    shield: cornex_right rgbled_adapter 

  - board: seeeduino_xiao_ble
    shield: settings_reset
