include:
  - board: seeeduino_xiao_ble
    shield: cornex_left nice_view
    # snippet: studio-rpc-usb-uart
    # cmake-args: -DCONFIG_ZMK_STUDIO=y

  - board: seeeduino_xiao_ble
    shield: cornex_right nice_view

  - board: seeeduino_xiao_ble
    shield: settings_reset